[package]
name = "bc-ur-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbor = "0.4.1"
crc32fast = "1.3.2"
hex = "0.4.3"
lazy_static = "1.4.0"